document.getElementById('first-button').addEventListener("click", function() {
  document.getElementById('second-button').classList.remove('minus-img')
  document.getElementById('third-button').classList.remove('minus-img')
  document.getElementById('fourth-button').classList.remove('minus-img')
  document.getElementById('fifth-button').classList.remove('minus-img')
  document.getElementById('sixth-button').classList.remove('minus-img')
  document.getElementById('second-question').classList.remove('show-answer')
  document.getElementById('third-question').classList.remove('show-answer')
  document.getElementById('fourth-question').classList.remove('show-answer')
  document.getElementById('fifth-question').classList.remove('show-answer')
  document.getElementById('sixth-question').classList.remove('show-answer')
  document.getElementById('first-button').classList.toggle('minus-img')
  document.getElementById('first-question').classList.toggle('show-answer')
})
document.getElementById('second-button').addEventListener("click", function() {
  document.getElementById('first-button').classList.remove('minus-img')
  document.getElementById('third-button').classList.remove('minus-img')
  document.getElementById('fourth-button').classList.remove('minus-img')
  document.getElementById('fifth-button').classList.remove('minus-img')
  document.getElementById('sixth-button').classList.remove('minus-img')
  document.getElementById('first-question').classList.remove('show-answer')
  document.getElementById('third-question').classList.remove('show-answer')
  document.getElementById('fourth-question').classList.remove('show-answer')
  document.getElementById('fifth-question').classList.remove('show-answer')
  document.getElementById('sixth-question').classList.remove('show-answer')
  document.getElementById('second-button').classList.toggle('minus-img')
  document.getElementById('second-question').classList.toggle('show-answer')
})
document.getElementById('third-button').addEventListener("click", function() {
  document.getElementById('first-button').classList.remove('minus-img')
  document.getElementById('second-button').classList.remove('minus-img')
  document.getElementById('fourth-button').classList.remove('minus-img')
  document.getElementById('fifth-button').classList.remove('minus-img')
  document.getElementById('sixth-button').classList.remove('minus-img')
  document.getElementById('first-question').classList.remove('show-answer')
  document.getElementById('second-question').classList.remove('show-answer')
  document.getElementById('fourth-question').classList.remove('show-answer')
  document.getElementById('fifth-question').classList.remove('show-answer')
  document.getElementById('sixth-question').classList.remove('show-answer')
  document.getElementById('third-button').classList.toggle('minus-img')
  document.getElementById('third-question').classList.toggle('show-answer')
})
document.getElementById('fourth-button').addEventListener("click", function() {
  document.getElementById('first-button').classList.remove('minus-img')
  document.getElementById('second-button').classList.remove('minus-img')
  document.getElementById('third-button').classList.remove('minus-img')
  document.getElementById('fifth-button').classList.remove('minus-img')
  document.getElementById('sixth-button').classList.remove('minus-img')
  document.getElementById('first-question').classList.remove('show-answer')
  document.getElementById('second-question').classList.remove('show-answer')
  document.getElementById('third-question').classList.remove('show-answer')
  document.getElementById('fifth-question').classList.remove('show-answer')
  document.getElementById('sixth-question').classList.remove('show-answer')
  document.getElementById('fourth-button').classList.toggle('minus-img')
  document.getElementById('fourth-question').classList.toggle('show-answer')
})
document.getElementById('fifth-button').addEventListener("click", function() {
  document.getElementById('first-button').classList.remove('minus-img')
  document.getElementById('second-button').classList.remove('minus-img')
  document.getElementById('third-button').classList.remove('minus-img')
  document.getElementById('fourth-button').classList.remove('minus-img')
  document.getElementById('sixth-button').classList.remove('minus-img')
  document.getElementById('first-question').classList.remove('show-answer')
  document.getElementById('second-question').classList.remove('show-answer')
  document.getElementById('third-question').classList.remove('show-answer')
  document.getElementById('fourth-question').classList.remove('show-answer')
  document.getElementById('sixth-question').classList.remove('show-answer')
  document.getElementById('fifth-button').classList.toggle('minus-img')
  document.getElementById('fifth-question').classList.toggle('show-answer')
})
document.getElementById('sixth-button').addEventListener("click", function() {
  document.getElementById('first-button').classList.remove('minus-img')
  document.getElementById('second-button').classList.remove('minus-img')
  document.getElementById('third-button').classList.remove('minus-img')
  document.getElementById('fourth-button').classList.remove('minus-img')
  document.getElementById('fifth-button').classList.remove('minus-img')
  document.getElementById('first-question').classList.remove('show-answer')
  document.getElementById('second-question').classList.remove('show-answer')
  document.getElementById('third-question').classList.remove('show-answer')
  document.getElementById('fourth-question').classList.remove('show-answer')
  document.getElementById('fifth-question').classList.remove('show-answer')
  document.getElementById('sixth-button').classList.toggle('minus-img')
  document.getElementById('sixth-question').classList.toggle('show-answer')
})
document.getElementById('booking-card').addEventListener("click", function() {
  document.getElementById('eco-main').classList.add('hide-content')
  document.getElementById('eco-booking').classList.add('show-content')
  document.getElementById('eco-go').classList.remove('show-content')
  document.getElementById('eco-relax').classList.remove('show-content')
  document.getElementById('eco-feeds').classList.remove('show-content')
  document.getElementById('eco-beautiful').classList.remove('show-content')
  document.getElementById('eco-pay').classList.remove('show-content')

  document.getElementById('booking-card').classList.add('active-card')
  document.getElementById('booking-card').classList.remove('inactive-card')
  document.getElementById('booking-img').classList.add('active-img')

  document.getElementById('go-card').classList.add('inactive-card')
  document.getElementById('go-card').classList.remove('active-card')
  document.getElementById('go-img').classList.remove('active-img')

  document.getElementById('relax-card').classList.add('inactive-card')
  document.getElementById('relax-card').classList.remove('active-card')
  document.getElementById('relax-img').classList.remove('active-img')

  document.getElementById('feeds-card').classList.add('inactive-card')
  document.getElementById('feeds-card').classList.remove('active-card')
  document.getElementById('feeds-img').classList.remove('active-img')

  document.getElementById('beautiful-card').classList.add('inactive-card')
  document.getElementById('beautiful-card').classList.remove('active-card')
  document.getElementById('beautiful-img').classList.remove('active-img')

  document.getElementById('pay-card').classList.add('inactive-card')
  document.getElementById('pay-card').classList.remove('active-card')
  document.getElementById('pay-img').classList.remove('active-img')
})
document.getElementById('go-card').addEventListener("click", function() {
  document.getElementById('eco-main').classList.add('hide-content')
  document.getElementById('eco-go').classList.add('show-content')
  document.getElementById('eco-booking').classList.remove('show-content')
  document.getElementById('eco-relax').classList.remove('show-content')
  document.getElementById('eco-feeds').classList.remove('show-content')
  document.getElementById('eco-beautiful').classList.remove('show-content')
  document.getElementById('eco-pay').classList.remove('show-content')

  document.getElementById('booking-card').classList.remove('active-card')
  document.getElementById('booking-card').classList.add('inactive-card')
  document.getElementById('booking-img').classList.remove('active-img')

  document.getElementById('go-card').classList.remove('inactive-card')
  document.getElementById('go-card').classList.add('active-card')
  document.getElementById('go-img').classList.add('active-img')

  document.getElementById('relax-card').classList.add('inactive-card')
  document.getElementById('relax-card').classList.remove('active-card')
  document.getElementById('relax-img').classList.remove('active-img')

  document.getElementById('feeds-card').classList.add('inactive-card')
  document.getElementById('feeds-card').classList.remove('active-card')
  document.getElementById('feeds-img').classList.remove('active-img')

  document.getElementById('beautiful-card').classList.add('inactive-card')
  document.getElementById('beautiful-card').classList.remove('active-card')
  document.getElementById('beautiful-img').classList.remove('active-img')

  document.getElementById('pay-card').classList.add('inactive-card')
  document.getElementById('pay-card').classList.remove('active-card')
  document.getElementById('pay-img').classList.remove('active-img')
})
document.getElementById('relax-card').addEventListener("click", function() {
  document.getElementById('eco-main').classList.add('hide-content')
  document.getElementById('eco-relax').classList.add('show-content')
  document.getElementById('eco-booking').classList.remove('show-content')
  document.getElementById('eco-go').classList.remove('show-content')
  document.getElementById('eco-feeds').classList.remove('show-content')
  document.getElementById('eco-beautiful').classList.remove('show-content')
  document.getElementById('eco-pay').classList.remove('show-content')

  document.getElementById('booking-card').classList.remove('active-card')
  document.getElementById('booking-card').classList.add('inactive-card')
  document.getElementById('booking-img').classList.remove('active-img')

  document.getElementById('go-card').classList.add('inactive-card')
  document.getElementById('go-card').classList.remove('active-card')
  document.getElementById('go-img').classList.remove('active-img')

  document.getElementById('relax-card').classList.remove('inactive-card')
  document.getElementById('relax-card').classList.add('active-card')
  document.getElementById('relax-img').classList.add('active-img')

  document.getElementById('feeds-card').classList.add('inactive-card')
  document.getElementById('feeds-card').classList.remove('active-card')
  document.getElementById('feeds-img').classList.remove('active-img')

  document.getElementById('beautiful-card').classList.add('inactive-card')
  document.getElementById('beautiful-card').classList.remove('active-card')
  document.getElementById('beautiful-img').classList.remove('active-img')

  document.getElementById('pay-card').classList.add('inactive-card')
  document.getElementById('pay-card').classList.remove('active-card')
  document.getElementById('pay-img').classList.remove('active-img')
})
document.getElementById('feeds-card').addEventListener("click", function() {
  document.getElementById('eco-main').classList.add('hide-content')
  document.getElementById('eco-feeds').classList.add('show-content')
  document.getElementById('eco-booking').classList.remove('show-content')
  document.getElementById('eco-go').classList.remove('show-content')
  document.getElementById('eco-relax').classList.remove('show-content')
  document.getElementById('eco-beautiful').classList.remove('show-content')
  document.getElementById('eco-pay').classList.remove('show-content')

  document.getElementById('booking-card').classList.remove('active-card')
  document.getElementById('booking-card').classList.add('inactive-card')
  document.getElementById('booking-img').classList.remove('active-img')

  document.getElementById('go-card').classList.add('inactive-card')
  document.getElementById('go-card').classList.remove('active-card')
  document.getElementById('go-img').classList.remove('active-img')

  document.getElementById('relax-card').classList.add('inactive-card')
  document.getElementById('relax-card').classList.remove('active-card')
  document.getElementById('relax-img').classList.remove('active-img')

  document.getElementById('feeds-card').classList.remove('inactive-card')
  document.getElementById('feeds-card').classList.add('active-card')
  document.getElementById('feeds-img').classList.add('active-img')

  document.getElementById('beautiful-card').classList.add('inactive-card')
  document.getElementById('beautiful-card').classList.remove('active-card')
  document.getElementById('beautiful-img').classList.remove('active-img')

  document.getElementById('pay-card').classList.add('inactive-card')
  document.getElementById('pay-card').classList.remove('active-card')
  document.getElementById('pay-img').classList.remove('active-img')
})
document.getElementById('beautiful-card').addEventListener("click", function() {
  document.getElementById('eco-main').classList.add('hide-content')
  document.getElementById('eco-beautiful').classList.add('show-content')
  document.getElementById('eco-booking').classList.remove('show-content')
  document.getElementById('eco-go').classList.remove('show-content')
  document.getElementById('eco-relax').classList.remove('show-content')
  document.getElementById('eco-feeds').classList.remove('show-content')
  document.getElementById('eco-pay').classList.remove('show-content')

  document.getElementById('booking-card').classList.remove('active-card')
  document.getElementById('booking-card').classList.add('inactive-card')
  document.getElementById('booking-img').classList.remove('active-img')

  document.getElementById('go-card').classList.add('inactive-card')
  document.getElementById('go-card').classList.remove('active-card')
  document.getElementById('go-img').classList.remove('active-img')

  document.getElementById('relax-card').classList.add('inactive-card')
  document.getElementById('relax-card').classList.remove('active-card')
  document.getElementById('relax-img').classList.remove('active-img')

  document.getElementById('feeds-card').classList.add('inactive-card')
  document.getElementById('feeds-card').classList.remove('active-card')
  document.getElementById('feeds-img').classList.remove('active-img')

  document.getElementById('beautiful-card').classList.remove('inactive-card')
  document.getElementById('beautiful-card').classList.add('active-card')
  document.getElementById('beautiful-img').classList.add('active-img')

  document.getElementById('pay-card').classList.add('inactive-card')
  document.getElementById('pay-card').classList.remove('active-card')
  document.getElementById('pay-img').classList.remove('active-img')
})
document.getElementById('pay-card').addEventListener("click", function() {
  document.getElementById('eco-main').classList.add('hide-content')
  document.getElementById('eco-pay').classList.add('show-content')
  document.getElementById('eco-booking').classList.remove('show-content')
  document.getElementById('eco-go').classList.remove('show-content')
  document.getElementById('eco-relax').classList.remove('show-content')
  document.getElementById('eco-feeds').classList.remove('show-content')
  document.getElementById('eco-beautiful').classList.remove('show-content')

  document.getElementById('booking-card').classList.remove('active-card')
  document.getElementById('booking-card').classList.add('inactive-card')
  document.getElementById('booking-img').classList.remove('active-img')

  document.getElementById('go-card').classList.add('inactive-card')
  document.getElementById('go-card').classList.remove('active-card')
  document.getElementById('go-img').classList.remove('active-img')

  document.getElementById('relax-card').classList.add('inactive-card')
  document.getElementById('relax-card').classList.remove('active-card')
  document.getElementById('relax-img').classList.remove('active-img')

  document.getElementById('feeds-card').classList.add('inactive-card')
  document.getElementById('feeds-card').classList.remove('active-card')
  document.getElementById('feeds-img').classList.remove('active-img')

  document.getElementById('beautiful-card').classList.add('inactive-card')
  document.getElementById('beautiful-card').classList.remove('active-card')
  document.getElementById('beautiful-img').classList.remove('active-img')

  document.getElementById('pay-card').classList.remove('inactive-card')
  document.getElementById('pay-card').classList.add('active-card')
  document.getElementById('pay-img').classList.add('active-img')
})